# Generated by Django 3.2.4 on 2021-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='hint',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
