# Generated by Django 3.2.4 on 2021-07-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_chapter_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='hint',
        ),
    ]
